const pics = [
    {
        id:1,
        pic : "aYear/teleferik.jpg",
        flip : "aYear/teleferikFlip.jpg",
        date:"1 Agustos",
    },
    {
        id:2,
        pic : "aYear/cay.jpg",
        flip : "aYear/cayFlip.jpg",
        date:"1 Agustos",
    },
    {
        id:3,
        pic : "aYear/havuz.jpg",
        flip : "aYear/havuzFlip.jpg",
        date:"31 Temmuz",
    },
    {
        id:4,
        pic : "aYear/mardin.jpg",
        flip : "aYear/mardinFlip.jpg",
        date:"7 Agustos",
    },
    {
        id:5,
        pic : "aYear/irem.jpg",
        flip : "aYear/iremFlip.jpg",
        date:"1 Agustos",
    },
    {
        id:6,
        pic : "aYear/jakuzi.jpg",
        flip : "aYear/jakuziFlip.jpg",
        date:"30 Temmuz",
    },
    {
        id:7,
        pic : "aYear/hivroj.jpg",
        flip : "aYear/hivrojFlip.jpg",
        date:"10 Agustos",
    },
    {
        id:8,
        pic : "aYear/suna.jpg",
        flip : "aYear/sunaFlip.jpg",
        date:"4 Agustos",
    },
    {
        id:9,
        pic : "aYear/kaan.jpg",
        flip : "aYear/kaanFlip.jpg",
        date:"30 Haziran",
    },
    {
        id:10,
        pic : "aYear/manzara.jpg",
        flip : "aYear/manzaraFlip.jpg",
        date:"1 Agustos",
    },
    {
        id:11,
        pic : "aYear/kapadokya.jpg",
        flip : "aYear/kapadokyaFlip.jpg",
        date:"26 Ekim",
    },
    {
        id:12,
        pic : "aYear/gelDamat.jpg",
        flip : "aYear/gelDamatFlip.jpg",
        date:"27 Temmuz",
    },
    {
        id:13,
        pic : "aYear/araba.jpg",
        flip : "aYear/arabaFlip.jpg",
        date:"27 temmuz",
    },
    {
        id:14,
        pic : "aYear/ulus.jpg",
        flip : "aYear/ulusFlip.jpg",
        date:"30 Haziran",
    },
    {
        id:15,
        pic : "aYear/maske.jpg",
        flip : "aYear/maskeFlip.jpg",
        date:"16 Haziran",
    },
    {
        id:16,
        pic : "aYear/cafe.jpg",
        flip : "aYear/cafeFlip.jpg",
        date:"5 Nisan",
    },
]
