const pics = [
    {
        id:1,
        pic : "https://hediyapp.herokuapp.com/aYear/teleferik.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/teleferikFlip.jpg",
        date:"1 Agustos",
    },
    {
        id:2,
        pic : "https://hediyapp.herokuapp.com/aYear/cay.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/cayFlip.jpg",
        date:"1 Agustos",
    },
    {
        id:3,
        pic : "https://hediyapp.herokuapp.com/aYear/havuz.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/havuzFlip.jpg",
        date:"31 Temmuz",
    },
    {
        id:4,
        pic : "https://hediyapp.herokuapp.com/aYear/mardin.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/mardinFlip.jpg",
        date:"7 Agustos",
    },
    {
        id:5,
        pic : "https://hediyapp.herokuapp.com/aYear/irem.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/iremFlip.jpg",
        date:"1 Agustos",
    },
    {
        id:6,
        pic : "https://hediyapp.herokuapp.com/aYear/jakuzi.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/jakuziFlip.jpg",
        date:"30 Temmuz",
    },
    {
        id:7,
        pic : "https://hediyapp.herokuapp.com/aYear/hivroj.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/hivrojFlip.jpg",
        date:"10 Agustos",
    },
    {
        id:8,
        pic : "https://hediyapp.herokuapp.com/aYear/suna.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/sunaFlip.jpg",
        date:"4 Agustos",
    },
    {
        id:9,
        pic : "https://hediyapp.herokuapp.com/aYear/kaan.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/kaanFlip.jpg",
        date:"30 Haziran",
    },
    {
        id:10,
        pic : "https://hediyapp.herokuapp.com/aYear/manzara.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/manzaraFlip.jpg",
        date:"1 Agustos",
    },
    {
        id:11,
        pic : "https://hediyapp.herokuapp.com/aYear/kapadokya.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/kapadokyaFlip.jpg",
        date:"26 Ekim",
    },
    {
        id:12,
        pic : "https://hediyapp.herokuapp.com/aYear/gelDamat.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/gelDamatFlip.jpg",
        date:"27 Temmuz",
    },
    {
        id:13,
        pic : "https://hediyapp.herokuapp.com/aYear/araba.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/arabaFlip.jpg",
        date:"27 temmuz",
    },
    {
        id:14,
        pic : "https://hediyapp.herokuapp.com/aYear/ulus.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/ulusFlip.jpg",
        date:"30 Haziran",
    },
    {
        id:15,
        pic : "https://hediyapp.herokuapp.com/aYear/maske.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/maskeFlip.jpg",
        date:"16 Haziran",
    },
    {
        id:16,
        pic : "https://hediyapp.herokuapp.com/aYear/cafe.jpg",
        flip : "https://hediyapp.herokuapp.com/aYear/cafeFlip.jpg",
        date:"5 Nisan",
    },
]
